### PR TITLE
Add bok-choy coverage.

### PR DESCRIPTION
**Pull request by benpatterson**
Previously we had inaccurate statistics for this metric. That's been
corrected with a job dedicated to calculating this data. Moved some
of the widgets in order to keep the page clean.

### CODE REVIEW

**Comment by benpatterson** [comment]
Here is a screenshot of how it will look now: 
image

**Comment by benpatterson** [comment]
@clytwynec @jzoldak

**Comment by jzoldak** [comment]
Can you please take a look at why migrations are being counted in the coverage? There is probably some typo in the regex. 
https://build.testeng.edx.org/view/All/job/bok-choy-coverage/18/cobertura/_default_/

**Comment by benpatterson** [comment]
@jzoldak here is a PR to fix that. https://github.com/edx/edx-platform/pull/7609

**Comment by jzoldak** [comment]
:+1:

**Pull request merged**
