### PR TITLE
Add ecom dashboard.

### PR DESCRIPTION
**Pull request by benpatterson**
This is a small/simple set of data: coveralls data for ecommerce & auth-backends repos

Screenshot:
image

### CODE REVIEW

**Comment by benpatterson** [comment]
@jzoldak @rlucioni

Can't add linting or acceptance coverage right now; those will need a bigger set of work I can't get to just yet. But I thought this could be useful.

**Comment by rlucioni** [comment]
Thanks for taking the time to do this @benpatterson. @jimabramson and @clintonb, is there anything else you'd like to see on this dashboard?

**Comment by clintonb** [comment]
:+1:

**Comment by rlucioni** [comment]
:+1:

**Comment by benpatterson** [comment]
Merging. Note that this will not cover the whole screen so it'll be an unbalanced page. I can put in a cycle to clean that up if it's going to make you twitch!

**Comment by rlucioni** [comment]
@benpatterson that might be nice! We'll survive otherwise though.

**Pull request merged**
